### ISSUE TITLE
Add projeto alvarofpp/python-adt-extension em _projects_hacktoberfest

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#11]
Python

https://github.com/alvarofpp/python-adt-extension

[você pode seguir esse artigo para fazer seu pr](https://jtemporal.com/adicionando-um-novo-projeto-na-lista-da-hacktoberfest-2019/)

**Comment by carolsoaressantos** [comment]
[Feito](https://github.com/jtemporal/jtemporal.github.io/pull/26)
