### ISSUE TITLE
Add projeto perfil-politico-frontend em JavaScript

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#126]
JavaScript

https://github.com/okfn-brasil/perfil-politico-frontend

[você pode seguir esse artigo para fazer seu pr](https://jtemporal.com/adicionando-um-novo-projeto-na-lista-da-hacktoberfest-2019/)

**Comment by di3goCS** [comment]
Mandei um PR!

**Comment by jtemporal** [comment]
fechado por engano. Essa issue ainda está disponível
