### ISSUE TITLE
Remover tag “title” não usada do projeto Bredis-session-storage

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#133]
projeto: [link](https://github.com/jtemporal/jtemporal.github.io/blob/main/_hacktoberfest_projects/JavaScript/rdiego26%2Bredis-session-storage.md)

basta apagar a linha correspondente a tag “title” já que ela não é usada na lista

**Comment by ilitotor** [comment]
Enviei um PR pra essa issue ;-)
