### ISSUE TITLE
Add projeto inspiradanacomputacao/tecnologistas-contra-bolsonaro em Variados

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#166]
Language: Variados

[repo url](https://github.com/inspiradanacomputacao/tecnologistas-contra-bolsonaro)

[você pode seguir esse artigo para fazer seu pr](https://jtemporal.com/adicionando-um-novo-projeto-na-lista-da-hacktoberfest-2019/)

**Comment by hi-hi-ray** [comment]
Eu ia vir aqui adicionar agora esse repo. haha Posso pegar a issue?

**Comment by jtemporal** [comment]
@hi-hi-ray claro! pode mandar o pr 😉

**Comment by hi-hi-ray** [comment]
Ebaa!! Esse fim de semana farei. Obrigada <3
