### ISSUE TITLE
Add projeto Tabnews em JavaScript

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#230]
JavaScript

[repo url](https://github.com/filipedeschamps/tabnews.com.br)

[você pode seguir esse artigo para fazer seu pr](https://jtemporal.com/adicionando-um-novo-projeto-na-lista-da-hacktoberfest-2019/)

**Comment by jovylle** [comment]
hey what to do. can I do this.

**Comment by letyhashimoto** [comment]
Oi Jess! Estava na live do GithubBrasil com vc e a Morganna. Posso pegar essa issue? 😊 quero tentar resolver uma issue. Ainda estou aprendendo.
