### ISSUE TITLE
Add codamos/codamos.github.io

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/jtemporal.github.io#24]
Variados

https://github.com/codamos/codamos.github.io/

[você pode seguir esse artigo para fazer seu pr](https://jtemporal.com/adicionando-um-novo-projeto-na-lista-da-hacktoberfest-2019/)

**Comment by carolsoaressantos** [comment]
Eu faço! :rocket:

**Comment by carolsoaressantos** [comment]
[Feito!](https://github.com/jtemporal/jtemporal.github.io/pull/25) :heart:
